apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  # Use LoadBalancer for AWS EKS to get an external URL
  type: LoadBalancer
