apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # echo -n 'admin' | base64     => YWRtaW4=
  # echo -n 'password123' | base64 => cGFzc3dvcmQxMjM=
  mongo-username: YWRtaW4=
  mongo-password: cGFzc3dvcmQxMjM=
